<?php
/**
 * Created by PhpStorm.
 * User: little-wei
 * Date: 2016/8/31
 * Time: 11:10
 */

namespace Qknow\Api\Updates;


use October\Rain\Database\Updates\Seeder;
use Qknow\Api\Models\Property;
use Qknow\Api\Models\PropertyDetails;
use Qknow\Api\Models\Video;

class SeedAllTables extends Seeder
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        Video::create([
            'parent_id' => 0,
            'category_id'=>1,
            'title'=>'chrome完全开发指南',
            'sub_title'=>'chrome开发高度技巧',
            'URL'=>'http://www.baidu.com',
            'difficulty'=>'初级',
            'image'=>'http://www.baidu.com',
            'time_length'=>50,
            'list_order'=>1,
            'display'=>1
        ]);

        Property::create([
            'name'=>'课程分类'
        ]);

        PropertyDetails::insert([
            [
                'property_id'=>1,
                'name'=>"HTML+CSS+JS"
            ],[
                'property_id'=>1,
                'name'=>"PHP"
            ],[
                'property_id'=>1,
                'name'=>"NODEJS"
            ]
        ]);

    }


}