<?php
/**
 * Created by PhpStorm.
 * User: little-wei
 * Date: 2016/8/31
 * Time: 11:10
 */

namespace Qknow\Api\Updates;


use October\Rain\Database\Updates\Seeder;
use Qknow\Api\Models\Chapter;
use Qknow\Api\Models\Course;
use Qknow\Api\Models\CourseType;
use Qknow\Api\Models\Statistic;
use Qknow\Api\Models\Video;


class SeedAllTables extends Seeder
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        CourseType::insert([
            [
                'course_type_name'=>'HTML+CSS+CSS',
                'image'=>'../images/web.jpg',
                'list_order'=>1
            ],
            [
                'course_type_name'=>'PHP',
                'image'=>'../images/php7.jpg',
                'list_order'=>2
            ],
            [
                'course_type_name'=>'NODE',
                'image'=>'../images/node.jpg',
                'list_order'=>3
            ],
            [
                'course_type_name'=>'WECHAT',
                'image'=>'../images/webchat.png',
                'list_order'=>4
            ],
            [
                'course_type_name'=>'LINUX',
                'image'=>'../images/linux.jpg',
                'list_order'=>5
            ],
            [
                'course_type_name'=>'TOOLS',
                'image'=>'../images/tool.jpg',
                'list_order'=>6
            ]

        ]);

        Course::insert([
            [
                'course_type_id'=>1,
                'lecturer_id'=>1,
                'statistice_id'=>1,
                'title'=>'chrome开发者完全指南',
                'sub_title'=>'chrome调试技巧',
                'image'=>'http://qknow.oss-cn-shanghai.aliyuncs.com/images/test03.jpg',
                'chapter_count'=>10,
                'time_length'=>50,
                'difficulty'=>'初级',
                'list_order'=>1
            ],
            [
                'course_type_id'=>2,
                'lecturer_id'=>1,
                'statistice_id'=>1,
                'title'=>'chrome开发者完全指南2',
                'sub_itle'=>'chrome调试技巧2',
                'images'=>'http://qknow.oss-cn-shanghai.aliyuncs.com/images/test03.jpg',
                'chapter_count'=>10,
                'time_length'=>50,
                'difficulty'=>'初级',
                'list_order'=>2
            ]
        ]);

        Chapter::insert([
            [
                'parent_id'=>0,
                'course_id'=>1,
                'video_id'=>0,
                'title'=>'第一章',
                'time_length'=>'10',
                'list_order'=>1
            ],
            [
                'parent_id'=>0,
                'course_id'=>1,
                'video_id'=>0,
                'title'=>'第二章',
                'time_length'=>'10',
                'list_order'=>2
            ],
            [
                'parent_id'=>1,
                'course_id'=>1,
                'title'=>'安装1',
                'video_id'=>1,
                'time_length'=>'10',
                'list_order'=>1
            ],
            [
                'parent_id'=>1,
                'course_id'=>1,
                'title'=>'测试1',
                'video_id'=>1,
                'time_length'=>'10',
                'list_order'=>2
            ],
            [
                'parent_id'=>2,
                'course_id'=>1,
                'title'=>'安装2',
                'video_id'=>1,
                'time_length'=>'10',
                'list_order'=>1
            ],
            [
                'parent_id'=>2,
                'course_id'=>1,
                'title'=>'测试2',
                'time_length'=>'10',
                'video_id'=>1,
                'list_order'=>2
            ]
        ]);

        Video::insert([
            [
                'URL'=>'http://qknow1.oss-cn-shanghai.aliyuncs.com/chrome_01_2016-08-29_222508.mp4',

            ],
            [
                'URL'=>'http://qknow1.oss-cn-shanghai.aliyuncs.com/chrome_01_2016-08-29_222508.mp4',

            ]

        ]);
        Statistic::insert([
            [
                'score'=>10,
                'sum'=>10000
            ]
        ]);


    }


}
