
//courseTypes
export const FETCH_COURSETYPES_SUCCESS='FETCH_COURSETYPES_SUCCESS';
export const FETCH_COURSETYPES_FAIL='FETCH_COURSETYPES_FAIL';


//course
export const  FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS' ;
export const  FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL' ;

export const  FETCH_COURSE_LIST_SUCCESS = 'FETCH_COURSE_LIST_SUCCESS' ;
export const  FETCH_COURSE_LIST_FAIL = 'FETCH_COURSE_LIST_FAIL' ;

//chapter
export const  FETCH_CHAPTER_LIST_SUCCESS = 'FETCH_CHAPTER_LIST_SUCCESS' ;
export const  FETCH_CHAPTER_LIST_FAIL = 'FETCH_CHAPTER_LIST_FAIL' ;

//videos
export const  FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS' ;
export const  FETCH_VIDEO_FAIL = 'FETCH_VIDEO_FAIL' ;
